#!/usr/bin/env bash
# Start a detached ReasoningBank runner without placing a credential in an
# argument, file generated by the run, or a second shell's environment.
set -euo pipefail
set +x

if [[ "$#" -eq 0 ]]; then
  echo "usage: REASONINGBANK_PROTECTED_ENV_FILE=/absolute/path $0 <runner-command...>" >&2
  exit 64
fi

protected_env_file="${REASONINGBANK_PROTECTED_ENV_FILE:-}"
if [[ -z "$protected_env_file" || "$protected_env_file" != /* || ! -f "$protected_env_file" ]]; then
  echo "REASONINGBANK_PROTECTED_ENV_FILE must name an existing absolute protected environment file" >&2
  exit 41
fi

# The protected file is deliberately sourced in this exact foreground process.
# `set -a` exports assignments that are shell-local in the source file; `exec`
# then guarantees that the Python runner has no intervening inheritance boundary.
set -a
# shellcheck source=/dev/null
source "$protected_env_file"
set +a
if [[ -z "${OPENROUTER_API_KEY:-}" ]]; then
  echo "OPENROUTER_API_KEY is unavailable in the protected launch environment" >&2
  exit 41
fi
export OPENROUTER_API_KEY
exec "$@"
